apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: marif-fargate
  region: us-east-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
